
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/tools"
  config.vm.network "private_network", ip: "192.168.10.10"
  config.vm.network "forwarded_port", guest: 8200, host: 8200
  config.vm.provision "file", source: "upstart/vault.conf", destination: "/home/vagrant/vault.conf"
  config.vm.provision "shell" do |s|
    s.inline = "cp /home/vagrant/vault.conf /etc/init/vault.conf"
    s.privileged = true
  end
  config.vm.provision "shell", inline: "vault server -dev -dev-root-token-id=root &"
end

